export const descEn = [
    [
        "Serious, calm, stable & peaceful.",
        "Pleased with facts, logical, objective, practical & realistic.",
        "Task-oriented, diligent, organized, promise-keeping, reliable & responsible.",
        "Good listener, loyal, only shares with close people.",
        "Holds rules, standards & procedures firmly.",
    ],
    [
        "Considerate, careful, meticulous and accurate.",
        "Serious, calm, stable yet sensitive.",
        "Friendly, considerate of others' feelings & needs, loyal, cooperative, good listener.",
        "Has organizational skills, detailed, meticulous, very responsible & reliable.",
    ],
    [
        "Quiet, reserved, tends to be rigid, cold, careful, considerate.",
        "Logical, rational, critical, objective, able to put feelings aside.",
        "Able to deal with sudden changes quickly and calmly.",
        "Confident, assertive and able to deal with differences and criticism.",
        "Able to analyze, organize, & delegate.",
        "Good problem solver especially for technical problems & sudden circumstances.",
    ],
    [
        "Simple-minded & practical, flexible, sensitive, friendly, self-effacing, humble in his/her abilities.",
        "Avoids conflict, does not impose his opinions or values on others.",
        "Usually unwilling to lead but a loyal follower and executor.",
        "Often relaxes about getting things done, enjoying what is happening in the moment.",
        "Shows more concern through actions than words.",
    ],
    [
        "Attentive, empathetic, sensitive & committed to a relationship.",
        "Success due to perseverance, originality and a strong desire to do whatever it takes including giving my best at work.",
        "Idealistic, perfectionist, firm in principles.",
        "Visionary, full of ideas, creative, thoughtful and inspiring.",
        "Usually followed and respected for clarity of vision and dedication to good things.",
    ],
    [
        "Visionary, has a practical plan, & usually has original ideas and a strong drive to achieve them.",
        "Independent and confident.",
        "Have good analytical skills and simplify complex and abstract things into something practical, easy to understand & practice.",
        "Skeptical, critical, logical, determinative and sometimes stubborn.",
        "Have a desire to develop and always want to be more advanced than others.",
        "Criticism & conflict are not a problem.",
    ],
    [
        "Very caring and sensitive to the feelings of others.",
        "Full of enthusiasm and loyalty, but usually only to close people.",
        "Cares about many things. Tends to take on too much and accomplish little.",
        "Tends to be idealistic and perfectionist.",
        "Thinks of win-win solutions, trusts and optimizes others.",
    ],
    [
        "Highly values intellect and knowledge. Enjoys theoretical and scientific matters. Likes to solve problems with logic and analysis.",
        "Quiet and restrained. Prefers to work alone.",
        "Tends to be critical, skeptical, suspicious and pessimistic.",
        "Does not like to lead and can be a undemanding follower.",
        "Tends to have clear interests. Needs a career where his interests can be developed and rewarding.",
        "If he finds something that interests him, he will be very serious and enthusiastic about it.",
    ],
    [
        "Spontaneous, active, energetic, dexterous, fast, alert, enthusiastic, fun and full of variety.",
        "Communicator, assertive, to the point, outspoken, charismatic, have good interpersonal skills.",
        "Good at on-the-spot problem solving. Able to deal with problems, conflicts and criticism. No worries, enjoys whatever happens.",
        "Tends to like something mechanistic, communal activities and sports.",
        "Adaptable, tolerant, generally conservative about values.",
        "Doesn't like too long explanations. Best at tangible things that can be done.",
    ],
    [
        "Outgoing, easygoing, easy to make friends, friendly, very social, outgoing, warm, & fun.",
        "Optimistic, cheerful, enthusiastic, fun, entertaining, likes to be noticed.",
        "Has good interpersonal skills, generous, easily sympathetic and recognizes the feelings of others.",
        "Avoid conflict and maintain the harmony of a relationship.",
        "Knows what is going on around her and participates in the activities.",
        "Excellent in situations that require common sense, quick action and practical skills.",
    ],
    [
        "Friendly, warm, energetic, optimistic, enthusiastic, high spirited, fun.",
        "Imaginative, full of ideas, creative, innovative.",
        "Able to adapt to various situations and changes.",
        "Good at communicating, happy to socialize & bring a positive atmosphere.",
        "Easy to read other people's feelings and needs.",
    ],
    [
        "Agile, creative, innovative, clever, logical, good at many things.",
        "Talkative and has good debating skills. Can argue for fun without feeling guilty.",
        "Flexible. Has many ways to solve problems and challenges.",
        "Less consistent. Tends to do something new and exciting after doing something else.",
        "Has a strong desire for self-improvement.",
    ],
    [
        "Practical, realistic, fact-based, with a natural drive for business and mechanistic.",
        "Very systematic, procedural and planned.",
        "Disciplined and hardworking.",
        "Conservative and tends to be rigid.",
        "Not interested in subjects that are not useful to him, but can adjust if necessary.",
        "Likes to organize things. Can be a good administrator if they remember to pay attention to other people's feelings and perspectives.",
    ],
    [
        "Warm, talkative, popular, born to cooperate, supportive and active group member.",
        "Needs balance and is good at creating harmony.",
        "Always does something nice for others. Works well in situations that support and praise it.",
        "Relaxed, easy going, simple, doesn't think things through.",
        "Meticulous and diligent in taking care of what she has.",
    ],
    [
        "Creative, imaginative, sensitive, loyal.",
        "Generally cares about what people say or what others want and tends to do things with other people's feelings in mind.",
        "Sociable, convincing, friendly, fun, popular, sympathetic. Responsive to criticism and praise.",
        "Likes variety and new challenges.",
        "Needs appreciation and acceptance.",
    ],
    [
        "Firm, assertive, to the point, straightforward, objective, critical, & has high standards.",
        "Dominant, strong willed, perfectionist and competitive.",
        "Tough, disciplined, and values commitment.",
        "Tends to mask feelings and hide weaknesses.",
        "Charismatic, good communication, able to mobilize people.",
        "Talented leader.",
    ],
]

export const descId = [
    [
        "Serius, tenang, stabil & damai.",
        "Senang pada fakta, logis, obyektif, praktis & realistis.",
        "Berorientasi pada tugas, tekun, teratur, menepati janji, dapat diandalkan & bertanggung jawab.",
        "Pendengar yang baik, setia, hanya mau berbagi dengan orang dekat.",
        "Memegang aturan, standar & prosedur dengan teguh.",
    ],
    [
        "Penuh pertimbangan, hati-hati, teliti dan akurat.",
        "Serius, tenang, stabil namun sensitif.",
        "Ramah, perhatian pada perasaan & kebutuhan orang lain, setia, kooperatif, pendengar yang baik.",
        "Punya kemampuan mengorganisasi, detail, teliti, sangat bertanggungjawab & bisa diandalkan.",
    ],
    [
        "Tenang, pendiam, cenderung kaku, dingin, hati-hati, penuh pertimbangan.",
        "Logis, rasional, kritis, obyektif, mampu mengesampingkan perasaan.",
        "Mampu menghadapi perubahan mendadak dengan cepat dan tenang.",
        "Percaya diri, tegas dan mampu menghadapi perbedaan maupun kritik.",
        "Mampu menganalisa, mengorganisir, & mendelegasikan.",
        "Problem solver yang baik terutama untuk masalah teknis & keadaan mendadak.",
    ],
    [
        "Berpikiran simpel & praktis, fleksibel, sensitif, ramah, tidak menonjolkan diri, rendah hati pada kemampuannya.",
        "Menghindari konflik, tidak memaksakan pendapat atau nilai-nilainya pada orang lain.",
        "Biasanya tidak mau memimpin tetapi menjadi pengikut dan pelaksana yang setia.",
        "Seringkali santai menyelesaikan sesuatu, karena sangat menikmati apa yang terjadi saat ini.",
        "Menunjukkan perhatian lebih banyak melalui tindakan dibandingkan kata-kata.",
    ],
    [
        "Perhatian, empati, sensitif & berkomitmen terhadap sebuah hubungan.",
        "Sukses karena ketekunan, originalitas dan keinginan kuat untuk melakukan apa saja yang diperlukan termasuk memberikan yg terbaik dalam pekerjaan.",
        "Idealis, perfeksionis, memegang teguh prinsip.",
        "Visioner, penuh ide, kreatif, suka merenung dan inspiring.",
        "Biasanya diikuti dan dihormati karena kejelasan visi serta dedikasi pada hal-hal baik.",
    ],
    [
        "Visioner, punya perencanaan praktis, & biasanya memiliki ide-ide original serta dorongan kuat untuk mencapainya.",
        "Mandiri dan percaya diri.",
        "Punya kemampuan analisa yang bagus serta menyederhanakan sesuatu yang rumit dan abstrak menjadi sesuatu yang praktis, mudah difahami & dipraktekkan.",
        "Skeptis, kritis, logis, menentukan (determinatif) dan kadang keras kepala.",
        "Punya keinginan untuk berkembang serta selalu ingin lebih maju dari orang lain.",
        "Kritik & konflik tidak menjadi masalah berarti.",
    ],
    [
        "Sangat perhatian dan peka dengan perasaan orang lain.",
        "Penuh dengan antusiasme dan kesetiaan, tapi biasanya hanya untuk orang dekat.",
        "Peduli pada banyak hal. Cenderung mengambil terlalu banyak dan menyelesaikan sebagian.",
        "Cenderung idealis dan perfeksionis.",
        "Berpikir win-win solution, mempercayai dan mengoptimalkan orang lain.",
    ],
    [
        "Sangat menghargai intelektualitas dan pengetahuan. Menikmati hal-hal teoritis dan ilmiah. Senang memecahkan masalah dengan logika dan analisa.",
        "Diam dan menahan diri. Lebih suka bekerja sendiri.",
        "Cenderung kritis, skeptis, mudah curiga dan pesimis.",
        "Tidak suka memimpin dan bisa menjadi pengikut yang tidak banyak menuntut.",
        "Cenderung memiliki minat yang jelas. Membutuhkan karir dimana minatnya bisa berkembang dan bermanfaat.",
        "Jika menemukan sesuatu yang menarik minatnya, ia akan sangat serius dan antusias menekuninya.",
    ],
    [
        "Spontan, Aktif, Enerjik, Cekatan, Cepat, Sigap, Antusias, Fun dan penuh variasi.",
        "Komunikator, asertif, to the point, ceplas-ceplos, berkarisma, punya interpersonal skill yang baik.",
        "Baik dalam pemecahan masalah langsung di tempat. Mampu menghadapi masalah, konflik dan kritik. Tidak khawatir, menikmati apapun yang terjadi.",
        "Cenderung untuk menyukai sesuatu yang mekanistis, kegiatan bersama dan olahraga.",
        "Mudah beradaptasi, toleran, pada umumnya konservatif tentang nilai-nilai.",
        "Tidak suka penjelasan terlalu panjang. Paling baik dalam hal-hal nyata yang dapat dilakukan.",
    ],
    [
        "Outgoing, easygoing, mudah berteman, bersahabat, sangat sosial, ramah, hangat, & menyenangkan.",
        "Optimis, ceria, antusias, fun, menghibur, suka menjadi perhatian.",
        "Punya interpersonal skill yang baik, murah hati, mudah simpatik dan mengenali perasaan orang lain.",
        "Menghindari konflik dan menjaga keharmonisan suatu hubungan.",
        "Mengetahui apa yang terjadi di sekelilingnya dan ikut serta dalam kegiatan tersebut.",
        "Sangat baik dalam keadaan yang membutuhkan common sense, tindakan cepat dan ketrampilan praktis.",
    ],
    [
        "Ramah, hangat, enerjik, optimis, antusias, semangat tinggi, fun.",
        "Imaginatif, penuh ide, kreatif, inovatif.",
        "Mampu beradaptasi dengan beragam situasi dan perubahan.",
        "Pandai berkomunikasi, senang bersosialisasi & membawa suasana positif.",
        "Mudah membaca perasaan dan kebutuhan orang lain.",
    ],
    [
        "Gesit, kreatif, inovatif, cerdik, logis, baik dalam banyak hal.",
        "Banyak bicara dan punya kemampuan debat yang baik. Bisa berargumentasi untuk senang-senang saja tanpa merasa bersalah.",
        "Fleksibel. Punya banyak cara untuk memecahkan masalah dan tantangan.",
        "Kurang konsisten. Cenderung untuk melakukan hal baru yang menarik hati setelah melakukan sesuatu yang lain.",
        "Punya keinginan kuat untuk mengembangkan diri.",
    ],
    [
        "Praktis, realistis, berpegang pada fakta, dengan dorongan alamiah untuk bisnis dan mekanistis.",
        "Sangat sistematis, procedural dan terencana.",
        "Disiplin dan pekerja keras.",
        "Konservatif dan cenderung kaku.",
        "Tidak tertarik pada subject yang tidak berguna baginya, tapi dapat menyesuaikan diri jika diperlukan.",
        "Senang mengorganisir sesuatu. Bisa menjadi administrator yang baik jika mereka ingat untuk memperhatikan perasaan dan perspektif orang lain.",
    ],
    [
        "Hangat, banyak bicara, populer, dilahirkan untuk bekerjasama, suportif dan anggota kelompok yang aktif.",
        "Membutuhkan keseimbangan dan baik dalam menciptakan harmoni.",
        "Selalu melakukan sesuatu yang manis bagi orang lain. Kerja dengan baik dalam situasi yang mendukung dan memujinya.",
        "Santai, easy going, sederhana, tidak berfikir panjang.",
        "Teliti dan rajin merawat apa yang ia miliki.",
    ],
    [
        "Kreatif, imajinatif, peka, sensitive, loyal.",
        "Pada umumnya peduli pada apa kata orang atau apa yang orang lain inginkan dan cenderung melakukan sesuatu dengan memperhatikan perasaan orang lain.",
        "Pandai bergaul, meyakinkan, ramah, fun, populer, simpatik. Responsif pada kritik dan pujian.",
        "Menyukai variasi dan tantangan baru.",
        "Butuh apresiasi dan penerimaan.",
    ],
    [
        "Tegas, asertif, to the point, jujur terus terang, obyektif, kritis, & punya standard tinggi.",
        "Dominan, kuat kemauannya, perfeksionis dan kompetitif.",
        "Tangguh, disiplin, dan sangat menghargai komitmen.",
        "Cenderung menutupi perasaan dan menyembunyikan kelemahan.",
        "Berkarisma, komunikasi baik, mampu menggerakkan orang.",
        "Berbakat pemimpin.",
    ],
]

export const advEn = [
    [
        "Learn to understand the feelings & needs of others.",
        "Reduce the desire to control others or boss them around to enforce rules.",
        "See more positives in people or things.",
        "Be open to change.",
    ],
    [   
        "Look deeper, be more enthusiastic, & more passionate.",
        "Learn to say 'no'. Don't please everyone or you'll come across as wishy-washy.",
        "Don't get stuck in your comfort zone and routine.",
        "Try new things. There are a lot of fun things you may not have tried yet.",
    ],
    [   
        "Observe social life, what makes people angry, love, happy, motivated & apply it to your relationships.",
        "Learn to recognize your feelings and express them.",
        "Be more open, get out of your comfort zone, explore new ideas, and discuss with others.",
        "Don't find fault with people just to solve their problems.",
        "Don't withhold information that should be shared and learn to entrust responsibility to others.",
    ],
    [   
        "Don't be afraid of rejection and conflict. You don't have to please everyone.",
        "Try to start thinking about the long-term impact of small decisions today.",
        "Hone and develop your creative and artistic side as a good asset in yourself.",
        "Try to be more open and express your feelings.",
    ],
    [   
        "Balance your perspective. Don't just look at the negatives & risks. Instead, look at the positives and opportunities.",
        "Be patient, don't get angry easily and blame others or the situation.",
        "Relax and don't keep thinking or completing responsibilities.",
    ],
    [   
        "Learn to express your emotions & feelings.",
        "Try to be more open to the outside world, socialize a lot, learn a lot, read a lot, visit a lot of places, explore new things, & broaden your horizons.",
        "Avoid unnecessary arguments.",
        "Learn to empathize, pay attention and be more sensitive to others.",
    ],
    [   
        "Learn to deal with criticism. If it's good then it can build you up, but if not just ignore it. Don't hesitate to ask questions and seek advice.",
        "Learn to be assertive. Don't always be heartless and please people with kind actions. Being nice is different from being right.",
        "Don't beat yourself up too much and be too hard on yourself. Failure is normal and everyone has experienced it.",
        "Don't be too kind to others and forget about yourself. You also have a responsibility to be kind to yourself.",
    ],
    [   
        "Learn to build relationships with others.",
        "Learn to empathize, listen actively, pay attention and exchange opinions.",
        "Relax. Don't think too much. Enjoy your life without asking why and how.",
        "Try to find one idea, plan and realize it.",
        "Don't change ideas too often but none of them materialize.",
    ],
    [   
        "Learn to understand other people's feelings and thoughts especially when talking to them.",
        "Learn to be patient, enjoy the process, not everything can be achieved quickly.",
        "Occasionally take time to reflect and plan your future.",
        "Try to record your observations including details.",
    ],
    [   
        "Don't rush into decisions. Learn to focus and not be fickle, especially on important matters.",
        "Don't please everyone. Vice versa, not everyone can please you.",
        "Learn to deal with criticism and conflict. Don't run away.",
        "You have meterialistic tendencies. Be careful, not everything can be measured by material or money.",
    ],
    [   
        "Learn to be focused, disciplined, firm and consistent.",
        "Learn to deal with conflict and criticism.",
        "Think of your own needs. Don't forget them because you care too much about other people's needs.",
        "Don't be too wasteful. Learn to manage your money little by little.",
    ],
    [   
        "Try for a win-win solution. Don't want to win alone.",
        "Learn to be disciplined and consistent.",
        "Avoid unnecessary arguments.",
        "Learn to be a little cautious. Balance your perspective to avoid being overly optimistic and taking unrealistic risks.",
        "Learn to pay attention to other people's feelings.",
    ],
    [   
        "Reduce the desire to control and force others.",
        "Learn to control your emotions and anger.",
        "Try to introspect yourself and take a moment to reflect.",
        "Learn to be more patient and humble.",
        "Learn to understand others.",
    ],
    [   
        "Don't sacrifice yourself just to please others.",
        "Do not measure your self-worth by the treatment, appreciation and praise of others.",
        "Ask for others' consideration in making decisions. Learn to be more assertive.",
        "Accept the responsibilities of life and learn to be more mature. Don't feel sorry for yourself.",
        "Face criticism and conflict, don't run away.",
    ],
    [   
        "Don't sacrifice yourself just to please others.",
        "Don't measure your self-worth by how others treat you. Don't be easily disappointed if they are not what you want them to be.",
        "Learn to be assertive and make decisions. Deal with criticism and conflict.",
        "Don't be too hard on yourself.",
    ],
    [   
        "Learn to relax. No need to be a perfectionist and always be competitive with everyone.",
        "Express your feelings. Expressing your feelings is not a weakness.",
        "Learn to manage your emotions. Don't get angry easily.",
        "Learn to respect and appreciate others.",
        "Don't be too arrogant and underestimate others. See the positive side. Don't just see right and wrong.",
    ],
]

export const advId = [
    [
        "Belajarlah memahami perasaan & kebutuhan orang lain.",
        "Kurangi keinginan untuk mengontrol orang lain atau memerintah mereka untuk menegakkan aturan.",
        "Lihatlah lebih banyak sisi positif pada orang lain atau hal lainnya.",
        "Terbukalah terhadap perubahan.",
    ],
    [   
        "Lihat lebih dalam, lebih antusias, & lebih semangat.",
        "Belajarlah mengatakan 'tidak'. Jangan menyenangkan semua orang atau kamu dianggap plin plan.",
        "Jangan terjebak zona nyaman dan rutinitas.",
        "Cobalah hal baru. Ada banyak hal menyenangkan yang mungkin belum pernah kamu coba.",
    ],
    [   
        "Observasilah kehidupan sosial, apa yang membuat orang marah, cinta, senang, termotivasi & terapkan pada hubungan kamu.",
        "Belajarlah untuk mengenali perasaan kamu dan mengekspresikannya.",
        "Jadilah orang yang lebih terbuka, keluar dari zona nyaman, eksplorasi ide baru, dan berdiskusi dengan orang lain.",
        "Jangan mencari-cari kesalahan orang hanya untuk menyelesaikan masalahnya.",
        "Jangan menyimpan informasi yang harusnya dibagi dan belajarlah mempercayakan tanggungjawab pada orang lain.",
    ],
    [   
        "Jangan takut pada penolakan dan konflik. Kamu tidak perlu menyenangkan semua orang.",
        "Cobalah untuk mulai memikirkan dampak jangka panjang dari keputusan-keputusan kecil di hari ini.",
        "Asah dan kembangkan sisi kreatifitas dan seni dalam diri kamu sebagai modal bagus dalam diri kamu.",
        "Cobalah untuk lebih terbuka dan mengekspresikan perasaan kamu.",
    ],
    [   
        "Seimbangkan cara pandang kamu. Jangan hanya melihat sisi negatif & resiko. Namun, lihatlah sisi positif dan peluangnya.",
        "Bersabarlah, jangan mudah marah dan menyalahkan orang lain atau situasi.",
        "Rileks dan jangan terus menerus berfikir atau menyelesaikan tanggung jawab.",
    ],
    [   
        "Belajarlah mengungkapkan emosi & perasaan kamu.",
        "Cobalah untuk lebih terbuka pada dunia luar, banyak bergaul, banyak belajar, banyak membaca, mengunjungi banyak tempat, eksplorasi hal baru, & memperluas wawasan.",
        "Hindari perdebatan tidak penting.",
        "Belajarlah untuk berempati, memberi perhatian dan lebih peka terhadap orang lain.",
    ],
    [   
        "Belajarlah menghadapi kritik. Jika baik maka kritik itu bisa membangun kamu, namun jika tidak abaikan saja. Jangan ragu pula untuk bertanya dan minta saran.",
        "Belajarlah untuk bersikap tegas. Jangan selalu berperasaan dan menyenangkan orang dengan tindakan baik. Bertindak baik itu berbeda dengan bertindak benar.",
        "Jangan terlalu menyalahkan diri dan bersikap terlalu keras pada diri sendiri. Kegagalan adalah hal biasa dan semua orang pernah mengalaminya.",
        "Jangan terlalu baik pada orang lain tapi melupakan diri sendiri. Kamu juga punya tanggungjawab untuk berbuat baik pada diri sendiri.",
    ],
    [   
        "Belajarlah membangun hubungan dengan orang lain.",
        "Belajar berempati, mendengar aktif, memberi perhatian dan bertukar pendapat.",
        "Relaks. Jangan terlalu banyak berfikir. Nikmati hidup kamu tanpa harus bertanya mengapa dan bagaimana.",
        "Cobalah menemukan satu ide, merencanakan dan mewujudkannya.",
        "Jangan terlalu sering berganti-ganti ide tetapi tidak satupun yang terwujud.",
    ],
    [   
        "Belajarlah memahami perasaan dan pemikiran orang lain terutama saat bicara dengan mereka.",
        "Belajarlah untuk sabar, menikmati proses, tidak semua hal bisa dicapai dengan cepat.",
        "Sesekali luangkan waktu untuk merenung dan merencanakan masa depan kamu.",
        "Cobalah untuk mencatat pengamatan-pengamatan kamu termasuk detailnya.",
    ],
    [   
        "Jangan terburu-buru dalam mengambil keputusan. Belajarlah untuk fokus dan tidak mudah berubah-ubah terutama untuk hal yang penting.",
        "Jangan menyenangkan semua orang. Begitu pula sebaliknya, tidak semua orang bisa menyenangkan kamu.",
        "Belajarlah menghadapi kritik dan konflik. Jangan lari.",
        "Kamu punya kecenderungan meterialistis. Hati-hati, tidak semua hal bisa diukur dengan materi ataupun uang.",
    ],
    [   
        "Belajarlah untuk fokus, disiplin, tegas dan konsisten.",
        "Belajarlah untuk menghadapi konflik dan kritik.",
        "Pikirkan kebutuhan diri sendiri. Jangan melupakannya karena terlalu peduli pada kebutuhan orang lain.",
        "Jangan terlalu boros. Belajarlah untuk mengelola keuangan sedikit demi sedikit.",
    ],
    [   
        "Cobalah untuk win-win solution. Jangan ingin menang sendiri.",
        "Belajarlah untuk disiplin dan konsisten.",
        "Hindari perdebatan tidak penting.",
        "Belajarlah untuk sedikit waspada. Seimbangkan cara pandang kamu agar tidak terlalu optimis dan mengambil resiko yang tidak realistis.",
        "Belajarlah untuk memberi perhatian pada perasaan orang lain.",
    ],
    [   
        "Kurangi keinginan untuk mengontrol dan memaksa orang lain.",
        "Belajarlah untuk mengontrol emosi dan amarah kamu.",
        "Cobalah untuk introspeksi diri dan meluangkan waktu sejenak untuk merenung.",
        "Belajarlah untuk lebih sabar dan rendah hati.",
        "Belajarlah untuk memahami orang lain.",
    ],
    [   
        "Jangan mengorbankan diri hanya untuk menyenangkan orang lain.",
        "Jangan mengukur harga diri kamu dari perlakuan, penghargaan dan pujian orang lain.",
        "Mintalah pertimbangan orang lain dalam mengambil keputusan. Belajarlah untuk lebih tegas.",
        "Terima tanggungjawab hidup dan belajarlah untuk lebih dewasa. Jangan mengasihani diri sendiri.",
        "Hadapi kritik dan konflik, jangan lari.",
    ],
    [   
        "Jangan mengorbankan diri hanya untuk menyenangkan orang lain.",
        "Jangan mengukur harga diri kamu dari perlakuan orang lain. Jangan mudah kecewa jika mereka tidak seperti yang kamu inginkan.",
        "Belajarlah untuk tegas dan mengambil keputusan. Menghadapi kritik dan konflik.",
        "Jangan terlalu bersikap keras terhadap diri sendiri.",
    ],
    [   
        "Belajarlah untuk relaks. Tidak perlu perfeksionis dan selalu kompetitif dengan semua orang.",
        "Ungkapkan perasaan kamu. Menyatakan perasaan bukanlah kelemahan.",
        "Belajarlah mengelola emosi kamu. Jangan mudah marah.",
        "Belajarlah untuk menghargai dan mengapresiasi orang lain.",
        "Jangan terlalu arogan dan menganggap remeh orang lain. Lihat sisi positifnya. Jangan hanya melihat benar dan salah saja.",
    ],
]
